apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airbyte-helm
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: "airbyte-v2 https://airbytehq.github.io/charts
      chart: airbyte
      targetRevision: "2.0.19"
      helm:
        releaseName: "airbyte"
        valueFiles:
          - $values/apps/airbyte-helm/dev/values.yaml

    - repoURL: "https://github.com/georgezefko/data-platform-engineering.git"
      targetRevision: HEAD
      ref: values
      path: apps/airbyte-helm/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: develop

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true